added markup and favicon
htmlacademy-htmlcss/2022859-sedona-36 pull request #2
Opened 2023-01-27 20:33 UTC by Yaroslav2769

2023-01-28 13:08 UTC, Yaroslav2769 commented
Я исправил некоторые ошибки, которые сам увидел

2023-01-28 13:29 UTC, summertime-fms requested changes

2023-01-28 13:29 UTC, summertime-fms commented on catalog.html
> +          <a class="navigation-link" href="#">Гостиницы</a>
Можно вообще href убрать тут, чтоб не кликалось даже.

2023-01-28 13:29 UTC, summertime-fms commented on catalog.html
> +            <img class="nav-icons" src="./images/Vector.svg" alt="search">
Иконки мелкие - это декоративные элементы, они либо стилями либо инлайновым svg вставляются (предпочтительный вариант). Убираем img)

2023-01-28 13:29 UTC, summertime-fms commented on catalog.html
> +            <img class="nav-icons" src="./images/Vector.svg" alt="search">
Ниже тоже

2023-01-28 13:29 UTC, summertime-fms commented on catalog.html
> +            <img class="nav-icons" src="./images/Vector-2.svg" alt="favourites">
Тоже убираем, а еще называть файлы надо без больших букв, как нибудь простенько. Типа iсon-fav.svg

2023-01-28 13:29 UTC, summertime-fms commented on catalog.html
> +            <span class="favourites"></span>
Это можно реализовать через псевдоэлементы в стилях, давай уберем. А вместо параграфа ниже сделаем span ибо параграф это все таки когда текста много

2023-01-28 13:29 UTC, summertime-fms commented on catalog.html
> +          <span>Хочу сюда</span>
Можно без спана)

2023-01-28 13:29 UTC, summertime-fms commented on catalog.html
> +        <form class="catalog-filter" action="https://echo.htmlacademy.ru/">
method забыл

2023-01-28 13:29 UTC, summertime-fms commented on catalog.html
> +                  <span class="filter-mark"></span>
Давай реализуем все на стилях, без лишних спанов в разметке, я покажу как это делать когда придет время. Пока же оставь инпуты с лейблами только

2023-01-28 13:29 UTC, summertime-fms commented on catalog.html
> +                  <input class="catalog-filter-input" type="checkbox">
А где name?

2023-01-28 13:29 UTC, summertime-fms commented on catalog.html
> +                  <input class="catalog-filter-input" type="radio">
name + value еще нужно

2023-01-28 13:29 UTC, summertime-fms commented on catalog.html
> +                  <input class="catalog-filter-input" type="radio">
И аналогично чекам, спаны пустые уберем давай.

2023-01-28 13:29 UTC, summertime-fms commented on catalog.html
> +              <label class="range-item">
А текст внутри лейблов где?

2023-01-28 13:29 UTC, summertime-fms commented on catalog.html
> +        <form class="sorting-index" action="#">
Я бы тут не стал в форму оборачивать, тут это допускается. Т.к. нет кнопки Отправить форму.

2023-01-28 13:29 UTC, summertime-fms commented on catalog.html
> +          <a class="sorting-link" href="#"></a>
Сгруппируем в див?

2023-01-28 13:29 UTC, summertime-fms commented on catalog.html
> +              <p class="catalog-item-description">Гостиница</p>
Наверное спаном лучше, т.к. одно слово всего.

2023-01-28 13:29 UTC, summertime-fms commented on catalog.html
> +                <button class="catalog-item-btn">
type button надо задать

2023-01-28 13:29 UTC, summertime-fms commented on catalog.html
> +                <ul class="rating-starts-wrapper">
Может просто img будем соответствующий подставлять? Кажется так будет короче разметка

2023-01-28 13:29 UTC, summertime-fms commented on catalog.html
> +               <a href="#">Рейтинг: <span>8,5</span></a>
А куда мы по клику переходить будем? мне кажется это не ссылка а просто текст.

2023-01-28 13:29 UTC, summertime-fms commented on catalog.html
> +        <h3 class="subscribe-title">Подпишитесь на рассылку</h3>
Дублирование. Оставь один h2. И получается он будет не скрытым уже.

2023-01-28 13:29 UTC, summertime-fms commented on catalog.html
> +        <form action="" class="appointment-form">
method

2023-01-28 13:29 UTC, summertime-fms commented on catalog.html
> +            <input class="field" type="text" placeholder="Ваш e-mail">
label

2023-01-28 13:29 UTC, summertime-fms commented on catalog.html
> +            <span class="visually-hidden">Вк</span>
Спан должен быть вложен в интерактивный элемент который он описывает. В данном случае в ссылку.

2023-01-28 13:29 UTC, summertime-fms commented on catalog.html
> +            <span class="visually-hidden">Вк</span>
А еще погугли про атрибуты nofollow noreferer, можно их тут заюзать)

2023-01-28 13:29 UTC, summertime-fms commented on catalog.html
> +      <div class="footer-phone">
Нет необходимости в диве. Ссылку блочной сделаем да и все.

2023-01-28 13:29 UTC, summertime-fms commented on catalog.html
> +      <div class="logo-html">
Аналогично.

2023-01-28 13:29 UTC, summertime-fms commented on catalog.html
> +          <img src="./images/logo_htmlacademy.svg" width="115px" height="33px" alt="">
Пиксели не указываются, невалидно будет. только цифра

2023-01-28 13:29 UTC, summertime-fms commented on index.html
> +        <img class="logo" src="./images/logo.svg" width="140" height="70" alt="Логотип Седона">
Лучше как в каталоге сделать в ссылку обернутым изображение. Только href на ставить. Потому что шапка это шаблонный элемент, он одинаковый на всех страницах (практически). И вот такие условия лучше не делать, что мол елси главная то не отрисовываем ссылку, а если не главная то добавляем. К тому же ты в каталоге скорее всего стилизовать лого будешь от класса ссылки. А тут ссылки нет и придется писать доп селектор. Надеюсь понятно объяснил

2023-01-28 13:29 UTC, summertime-fms commented on index.html
> +      <img class="vector" src="./images/Vector.png" width="1200" height="57" alt="Лесенка">
Декоративный элемент который можно сделать псевдоэлементом + bg-image

2023-01-28 13:29 UTC, summertime-fms commented on index.html
> +          <div class="texts-item">
В диве нет надобности

2023-01-28 13:29 UTC, summertime-fms commented on index.html
> +        <img src="./images/photo-1.jpg" width="800" height="384" alt="Настоящий городок">
Обернуть в li

2023-01-28 13:29 UTC, summertime-fms commented on index.html
> +       <ul class="advantage-list">
Можно не начинать новый список а продолжать старый, мне кажется

2023-01-28 13:29 UTC, summertime-fms commented on index.html
> +            <div class="service-content">
Нет необходимости в диве.

2023-01-28 13:29 UTC, summertime-fms commented on index.html
> +              <img class="advantage-service-icon" width="77" height="72" src="./images/Advantage-icon.svg" alt="housing">
Иконка декоративная

2023-01-28 13:29 UTC, summertime-fms commented on index.html
> +          <p class="interested-description">Укажите предполагаемые даты поездки,<br>и мы покажем вам лучшие предложения гостиниц в Седоне</p>
Дублировнаие заголовков, оставим один давай.

2023-01-28 15:07 UTC, Yaroslav2769 commented
Вроде все исправил, кроме advantage-list

2023-01-29 17:12 UTC, Yaroslav2769 commented
Все исправил

2023-01-30 11:10 UTC, Yaroslav2769 commented
Исправил

2023-01-30 14:13 UTC, merged